### ISSUE TITLE
Prepare release 0.2

### ISSUE THREAD

**Issue by dmitrii-khizbullin** [camel-ai/camel#285]
### Checklist

Close PRs:

- [x] #280 [not mature, may be removed]
- [x] #254 [the author is not there to finish this PR]
- [x] #274
- [x] #281
- [x] #243
- [ ] #202

Implement critical improvements:

- [x] #286
- [x] #287

Verify the release:

- [ ] Prepare release notes
- [ ] Look through the documentation
- [ ] Look through code coverage
- [ ] Update Jupyter examples
- [ ] Run a couple of example for the sanity check
- [ ] Make a release candidate branch, Increment version, put a tag

**Comment by dandansamax** [comment]
#243 How about adding this?

**Comment by Obs01ete** [comment]
> #243 How about adding this?

@lightaime should we include BabyAGI?

**Comment by lightaime** [comment]
Closed this since it is outdated
