### ISSUE TITLE
[Roadmap] RAG

### ISSUE THREAD

**Issue by Wendong-Fan** [camel-ai/camel#327]
### Phase 1 (Native RAG)
- [x] Integrate [[unstructured](https://unstructured.io/)] https://github.com/camel-ai/camel/pull/336
- [x] Integrate embedding model https://github.com/camel-ai/camel/pull/386
- [x] Integrate Vector DB https://github.com/camel-ai/camel/pull/380
- [x] rag function for agent https://github.com/camel-ai/camel/pull/410

### Phase 2 (Advanced RAG)
- [x] Integrate keyword search algorithm [BM25](https://github.com/dorianbrown/rank_bm25) https://github.com/camel-ai/camel/pull/410
- [x] Integrate re-rank model (commercial:[cohere rerank model](https://docs.cohere.com/reference/rerank-1?_gl=1*eepr09*_gcl_au*MjEwOTM0MzU1My4xNzAwMjk2OTI1*_ga*MTc3MTU0MjAzLjE3MDAyODc0NjE.*_ga_CRGS116RZS*MTcwNTYzOTc3OS41LjEuMTcwNTY0MDQyNC4yNy4wLjA.), open-source:[cross-encoder](https://huggingface.co/cross-encoder/ms-marco-MiniLM-L-2-v2?text=I+like+you.+I+love+you)) https://github.com/camel-ai/camel/pull/410
- [x] Integrate Knowledge Graph(https://github.com/camel-ai/camel/pull/450)
- [x] add RAG citation 

### Frame diagram

![Image](https://github.com/camel-ai/camel/assets/133094783/49e899f3-ca63-4da2-8c6a-4c7f416c9ffc)

**Comment by lightaime** [comment]
Closed this since it is outdated
