### ISSUE TITLE
[Roadmap] Add new OpenAI APIs

### ISSUE THREAD

**Issue by dandansamax** [camel-ai/camel#352]
- [x] #355
- [x] Introduce Pydantic types

Add new OpenAI Models:

- [x] `gpt-4-1106-preview` #357 
- [ ] `gpt-4-vision-preview`
- [x] `gpt-3.5-turbo-1106` #357
- [ ] `dall-e-3`
- [ ] Text to speech

Update chat completion API:

- [x] #368
- [ ] Reproducible outputs
- [ ] [Update function call API](https://platform.openai.com/docs/api-reference/chat/create#chat-create-tools)
- [x] [Retries](https://github.com/openai/openai-python#retries) #355
- [x] [Timeouts](https://github.com/openai/openai-python#timeouts) #355

**Comment by Wendong-Fan** [comment]
Closing due to outdated
