### ISSUE TITLE
[Roadmap] More chat modes

### ISSUE THREAD

**Issue by lightaime** [camel-ai/camel#59]
## Motivation

Now `CAMEL` apps only support chatting between two autonomous agents. It is important to support more chat modes for different use cases.

- [x] Autonomous chat with more than two agents
- [x] Chat with Human-in-the-loop (https://github.com/lightaime/camel/pull/77)
- [x] Support chatting with Human-in-the-loop in UI

Thanks @marchowardbegins for the discussion https://github.com/lightaime/camel/issues/57#issuecomment-1499796463

**Comment by marchowardbegins** [comment]
Thx for adding this @lightaime . Happy to help test the Human-in-the-Loop if you get this working. Lmk if you need anymore detail.

**Comment by lightaime** [comment]
Closed this since these features are supported
